# Generated by Django 2.2.1 on 2019-05-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(blank=True, choices=[('', '---')], default='', max_length=80, verbose_name='Link Type')),
                ('link_url', models.URLField(blank=True, default='', max_length=255, verbose_name='URL')),
                ('link_url_target', models.CharField(blank=True, choices=[('', 'same window'), ('_blank', 'new window')], default='', max_length=255, verbose_name='Target')),
                ('link_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
