# Generated by Django 2.2.1 on 2019-05-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_html', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Test model',
                'verbose_name_plural': 'Test models',
                'ordering': ['pk'],
            },
        ),
    ]
